###################  服务端口  ###################
server:
  port: 168

###################  spring配置  ###################
spring:
  application:
    name: dsp-admin
  datasource:
    url: jdbc:mysql://localhost:3306/make_money?characterEncoding=UTF8&serverTimezone=UTC&useSSL=false
    username: root
#    password: 210956
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:oracle:thin:@168.61.2.2:1521:servdb
#    username: dsp2
#    password: DS_P_2019
#    driver-class-name: oracle.jdbc.driver.OracleDriver

###################  redis 配置  ###################
  jedis:
    host: localhost
    port: 6379
    timeout: 30000
    pool:
      max-wait: 1
      max-active: 200
      max-idle: 8
      min-idle: 0
  mail:
    host: 168.61.10.118
    username: "006048"
    password: Admin@123
    default-encoding: UTF-8
    port: 25
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
        debug: true   （测试用）
###################  redisTemplate配置  ###################
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
    database: 8

###################  mybatis配置  ###################
mybatis:
  mapper-locations: classpath*:com/lucky/soon/**/mapping/*.xml

###################  输出sql语句  ###################
logging:
  level:
    root: INFO
    com.lucky.soon.dao: debug

